[build]
    command = "cd functions && npm i && cd .. && bundle exec jekyll build"
    publish = "_site"
    functions = "functions"
[context.dev.environment]
    PRICE_ID_40 = "price_1JB5mPLWJ8yP5sOTiCtyPMTw"
    SHIPPING_RATE_AMERICA = "shr_1JB7YKLWJ8yP5sOTlCUcbR5i"
    STRIPE_SECRET_KEY = "sk_test_51IKoNALWJ8yP5sOT2o0gykDjMK2C6PyrUhj1pe0udtJP09u2iIxaSyZ1QvSqTy5EzZ3nviNqRiW5COifRls4dGpj00mXl2Pasa"
    STRIPE_PUBLISHABLE_KEY = "pk_test_51IKoNALWJ8yP5sOTIOdFOX2I8cDFhJFsRe7hjGbNyK8BQR9MnpWAjO5E7fNMgWmm1fzdPVIE1XFNIC7CqX3xUJFY00EVYKXR0Q"
    STRIPE_WEBHOOK_SECRET = "whsec_AzHQVYykKm8S4hMGdUEItyjXoEMWehZw"
    EASYPOST_API_KEY = "EZTKf7234c3478244b0997779c453460d4b7SNt24v3Au0QYUHh7m6oXxg"
    # STRIPE_COUPON_ID = "l980mL1v"
    STRIPE_COUPON_ID = "72ZGtasi"
